# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."luks-8f68e355-9979-4e63-ae1c-6c8ff6561073".device =
    "/dev/disk/by-uuid/8f68e355-9979-4e63-ae1c-6c8ff6561073";

  fileSystems = {
    "/" = {
      device = "/dev/mapper/luks-8f68e355-9979-4e63-ae1c-6c8ff6561073";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/344C-8B1E";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };

    "/games" = {
      device = "/dev/disk/by-uuid/7cac66eb-6857-4a38-a9c6-33326083b69b";
      fsType = "ext4";
    };
  };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
